spring.application.name=elbuensabor
spring.datasource.url=jdbc:mysql://localhost:3306/elbuensabor
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=debug

spring.jpa.hibernate.ddl-auto=update

# Directorio de subida
app.upload-dir=./uploads/products

mercadopago.access-token=APP_USR-1160846029904701-121509-601051a6c232c0fd41c72dac43ed59ec-3063228874